services:
  api:
    build:
      api/
    env_file:
      ./.env
    ports:
      - "3024:3024"
    networks:
      - grafana_network
    volumes:
      - type: bind
        source: ./database
        target: /database
      - type: bind
        source: ./logs
        target: /logs
      - type: bind
        source: ./common_utils
        target: /common_utils

  main_bot:
    build:
      bot/
    env_file:
      ./.env
    networks:
      - grafana_network
    volumes:
      - type: bind
        source: ./database
        target: /database
      - type: bind
        source: ./logs
        target: /logs
      - type: bind
        source: ./common_utils
        target: /common_utils


networks:
  grafana_network:
    external: true
