services:
  api:
    build:
      api/
    env_file:
      ./.env
    ports:
      - "3024:3024"
    networks:
      - grafana_network
    volumes:
      - type: bind
        source: ./database
        target: /database
      - type: bind
        source: ./logs
        target: /logs
      - type: bind
        source: ./common_utils
        target: /common_utils
      - type: bind
        source: ./resources
        target: /resources

  main_bot:
    build:
      bot/
    env_file:
      ./.env
    networks:
      - grafana_network
    volumes:
      - type: bind
        source: ./database
        target: /database
      - type: bind
        source: ./logs
        target: /logs
      - type: bind
        source: ./common_utils
        target: /common_utils
      - type: bind
        source: ./resources
        target: /resources

  custom_bots:
    build:
      custom_bots/
    env_file:
      ./.env
    ports:
      - "88:4444"
      - "7532:7532"
    networks:
      - grafana_network:
          ipv4_address: "171.30.0.24"
    volumes:
      - type: bind
        source: ./database
        target: /database
      - type: bind
        source: ./logs
        target: /logs
      - type: bind
        source: ./common_utils
        target: /common_utils
      - type: bind
        source: ./resources
        target: /resources


networks:
  grafana_network:
    external: true
