target-version = "py310"

line-length = 120
exclude = [
    "webapp",
    "web_app",
    "webapp_legacy"
]

[lint]
select = ["F", "E", "W", "PLE", "PLW", "ARG"]

[lint.per-file-ignores]
"__init__.py" = ["F401", "F403"]
"conftest.py" = ["ARG001", "F405"]
"tests/**/*" = ["ARG002"]
