import os

TRIAL_DURATION_IN_DAYS = 7
SUBSCRIPTION_DURATION_IN_DAYS = 31

NOTIFICATIONS_BEFORE_DAYS = [1, 3]

DESTINATION_PHONE_NUMBER = os.getenv("DESTINATION_PHONE_NUMBER")
SUBSCRIPTION_PRICE = 1990
