TRIAL_DURATION_IN_DAYS = 7
BIG_TRIAL_DURATION_IN_DAYS = 30
SUBSCRIPTION_DURATION_IN_DAYS = 31

NOTIFICATIONS_BEFORE_DAYS = [1, 3]

SUBSCRIPTION_PRICE = 1990

FIRST_REFERRAL_LAYER = 500
SECOND_REFERRAL_LAYER = 300
THIRD_REFERRAL_LAYER = 200
