"""init

Revision ID: 5273e9d542b9
Revises: 
Create Date: 2024-02-09 16:35:19.294863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from database.models.order_model import OrderStatus


# revision identifiers, used by Alembic.
revision: str = '5273e9d542b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_bot_users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=55), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('products',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=55), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('picture', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('from_user', sa.BigInteger(), nullable=True),
    sa.Column('ordered_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('status', OrderStatus(), nullable=True),
    sa.ForeignKeyConstraint(['from_user'], ['custom_bot_users.user_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('products')
    op.drop_table('custom_bot_users')
    # ### end Alembic commands ###
