"""init

Revision ID: a854af6b9a72
Revises: 
Create Date: 2024-02-12 22:00:35.463397

"""
from alembic import op
import sqlalchemy as sa
import database.models.order_model


# revision identifiers, used by Alembic.
revision = 'a854af6b9a72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bots',
    sa.Column('bot_token', sa.String(length=46), nullable=False),
    sa.Column('status', sa.String(length=55), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('bot_token')
    )
    op.create_table('custom_bot_users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=55), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=55), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('orders',
    sa.Column('id', sa.String(length=13), nullable=False),
    sa.Column('bot_token', sa.String(length=46), nullable=True),
    sa.Column('products_id', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('from_user', sa.BigInteger(), nullable=True),
    sa.Column('ordered_at', sa.DateTime(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('status', database.models.order_model.OrderStatus(), nullable=True),
    sa.ForeignKeyConstraint(['from_user'], ['custom_bot_users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('bot_token', sa.String(length=46), nullable=False),
    sa.Column('name', sa.String(length=55), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('picture', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bot_token'], ['bots.bot_token'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_table('users')
    op.drop_table('custom_bot_users')
    op.drop_table('bots')
    # ### end Alembic commands ###
