"""add bots table

Revision ID: c9d88a131668
Revises: 4958475a3368
Create Date: 2024-02-10 16:14:06.834974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9d88a131668'
down_revision: Union[str, None] = '4958475a3368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bots',
    sa.Column('bot_token', sa.String(length=46), nullable=False),
    sa.Column('status', sa.String(length=55), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('bot_token')
    )
    op.add_column('products', sa.Column('bot_token', sa.String(length=46), nullable=False))
    op.create_foreign_key(None, 'products', 'bots', ['bot_token'], ['bot_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'bot_token')
    op.drop_table('bots')
    # ### end Alembic commands ###
