name: ci
on:
  push:
    branches: [ master_debug, release_debug]
  pull_request:
    branches: [ master_debug ]

jobs:
  ci_job:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: set postgresql database for tests
          run: |
            sudo apt update
            sudo apt install postgresql postgresql-contrib
            sudo systemctl start postgresql.service
            sudo systemctl status postgresql.service
            cd /tmp
            sudo -u postgres psql -c "ALTER ROLE postgres WITH password 'password'"
        - name: install pip dependencies
          run: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r bot/requirements.txt
        - name: run db unit tests
          run: |
            export DEBUG=1
            export PROJECT_ROOT=/home/runner/work/EasyShop/EasyShop/
            export DB_FOR_TESTS=postgresql+asyncpg://postgres:password@localhost:5432/postgres
            mkdir database/logs
            . venv/bin/activate
            pytest -v
