name: ci
on:
  push:
    branches: [ master_debug, master_release ]
  pull_request:
    branches: [ master_debug ]

jobs:

  auto_deploy:
    if: github.event_name == 'push' && github.ref_name == 'master_debug'
    runs-on: ubuntu-latest
    steps:
        - name: install dependencies
          run: |
            sudo apt update
            sudo apt install sshpass
            sshpass -p "${{ secrets.HMM }}" ssh -o "StrictHostKeyChecking=no" -T ${{ secrets.USER }} -p 22 "bash autopull.sh & exit"

  ci_job:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: set postgresql database for tests
          run: |
            sudo apt update
            sudo apt install postgresql postgresql-contrib
            sudo systemctl start postgresql.service
            sudo systemctl status postgresql.service
            cd /tmp
            sudo -u postgres psql -c "ALTER ROLE postgres WITH password 'password'"
        - name: install pip dependencies
          run: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r bot/requirements.txt
        - name: run db unit tests
          run: |
            export DEBUG=1
            export PROJECT_ROOT=/home/runner/work/EasyShop/EasyShop/
            export FILES_PATH=/home/runner/work/EasyShop/EasyShop/Files/
            export DB_FOR_TESTS=postgresql+asyncpg://postgres:password@localhost:5432/postgres
            export SCHEDULER_FOR_TESTS=postgresql+psycopg2://postgres:password@localhost:5432/postgres
            export ADMINS=0
            export WEBHOOK_LOCAL_API_PORT=0
            export BOT_DEBUG_MODE=1
            export LOGS_PATH=$PROJECT_ROOTlogs/
            export DESTINATION_PHONE_NUMBER=+79778506494
            mkdir logs
            mkdir database/logs
            . venv/bin/activate
            pytest -v
