name: YC Tracker
on:
  pull_request:
    types:
      - opened
      - reopened
      - closed

jobs:
  move-task-when-pr-opened:
    runs-on: ubuntu-latest
    name: Pull requests opened
    if: github.event.action != 'closed'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Move status to Ревью
      run: >
        echo Starting working with ${{ github.event.pull_request.title }} &&
        curl
        --request POST
        --header 
        --url https://api.tracker.yandex.net/v2/issues/<ключ_или_идентификатор_задачи>/transitions/<идентификатор_перехода>/_execute
